/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ipc1.proyecto2.graficos;

import com.ipc1.proyecto2.controladorDamas.CuadrosFichas;
import javax.swing.JOptionPane;

/**
 *
 * @author minch
 */
public class TableroDamas2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private boolean terminar = false;
    private MenuJuegos menuJuegos;
    
    public TableroDamas2(MenuJuegos menuJuegos) {
        this.menuJuegos = menuJuegos;
        
        CronometroDamas crnmt = new CronometroDamas(this);
        initComponents();
        this.setLocationRelativeTo(null);
        new CuadrosFichas(this, crnmt, menuJuegos);
         
         Thread t = new Thread(crnmt);
        t.start();
         
    }

    public boolean getTerminar() {
        return terminar;
    }

    public void setTerminar(boolean terminar) {
        this.terminar = terminar;
    }

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rendirse = new javax.swing.JButton();
        guardarPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ValidarCierre(evt);
            }
        });

        rendirse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rendirse.setText("Rendirse");
        rendirse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rendirseMouseClicked(evt);
            }
        });
        rendirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendirseActionPerformed(evt);
            }
        });

        guardarPartida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        guardarPartida.setText("Guardar Partida");
        guardarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarPartidaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(rendirse)
                .addGap(100, 100, 100)
                .addComponent(guardarPartida)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(580, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rendirse)
                    .addComponent(guardarPartida))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rendirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendirseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rendirseActionPerformed

    private void rendirseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rendirseMouseClicked
        // TODO add your handling code here:
        rendirse();
        
        
        
          
        
    }//GEN-LAST:event_rendirseMouseClicked

    private void guardarPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarPartidaMouseClicked
        // TODO add your handling code here:
        Object[] options = {"SI", "NO"};
        Object c;
        c=JOptionPane.showOptionDialog(null, "Quieres Guardar la partida ", "Guardar",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                null, options, options[0]);

        if((int)c==0 ){
             terminar = true;
            dispose();
            menuJuegos.setVisible(true);
        }
    }//GEN-LAST:event_guardarPartidaMouseClicked

    private void ValidarCierre(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ValidarCierre
        // TODO add your handling code here:
        rendirse();
    }//GEN-LAST:event_ValidarCierre

    
    
    public void rendirse(){
        Object[] options = {"SI", "NO"};
        Object c;
            c=JOptionPane.showOptionDialog(null, "Quieres Abandonar la Partida \n       (perderas el Juego)", "RENDIRSE",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                null, options, options[0]);

        if((int)c==0 ){
             terminar = true;
            dispose();
            menuJuegos.setVisible(true);
        }
    
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarPartida;
    private javax.swing.JButton rendirse;
    // End of variables declaration//GEN-END:variables
}
