/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ipc1.proyecto3;

/**
 *
 * @author minch
 */
public class Cronometro extends javax.swing.JPanel {

   private int hora=01;
   private int minutos=01;
   private int segundos=01;
   
    public Cronometro() {
        initComponents();
        this.setBounds(350, 3, 225, 50);
        contador();
    }
    
    
    public void contador(){
        String actualizador = "hola";
     contador.setText(actualizador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contador = new javax.swing.JLabel();
        tiempoText = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contador.setText("00:00:00");
        contador.setToolTipText("");
        contador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 30));

        tiempoText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tiempoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempoText.setText("TIEMPO:");
        add(tiempoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contador;
    private javax.swing.JLabel tiempoText;
    // End of variables declaration//GEN-END:variables
}
