/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ipc1.proyecto3.graficos;

/**
 *
 * @author minch
 */
public class MenuJuegos extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuJuegos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        juegoDamas = new javax.swing.JButton();
        JuegoHanoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Menu de juegos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        juegoDamas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        juegoDamas.setText("Jugar Damas");
        juegoDamas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juegoDamasMouseClicked(evt);
            }
        });
        jPanel1.add(juegoDamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 260, -1));

        JuegoHanoi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JuegoHanoi.setText("Jugar Torres de Hanoi");
        JuegoHanoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JuegoHanoiMouseClicked(evt);
            }
        });
        jPanel1.add(JuegoHanoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juegoDamasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juegoDamasMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_juegoDamasMouseClicked

    private void JuegoHanoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JuegoHanoiMouseClicked
        // TODO add your handling code here:
        TorresdeHanoi ventanaHanoi = new TorresdeHanoi();
        ventanaHanoi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JuegoHanoiMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JuegoHanoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton juegoDamas;
    // End of variables declaration//GEN-END:variables
}
