/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ipc1.proyecto3.graficos;

/**
 *
 * @author minch
 */
public class MenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form MenuDeJuegos
     */
    public MenuUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        crearUsuario = new javax.swing.JButton();
        elegirUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        crearUsuario.setText("CREAR USUARIO");
        crearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearUsuarioMouseClicked(evt);
            }
        });
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(crearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        elegirUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        elegirUsuario.setText("ELEGIR USUARIO");
        elegirUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elegirUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(elegirUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("MENU INICIAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearUsuarioActionPerformed

    private void crearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearUsuarioMouseClicked
        // TODO add your handling code here:
        Prueba prub = new Prueba();
        prub.setVisible(true);
    }//GEN-LAST:event_crearUsuarioMouseClicked

    private void elegirUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elegirUsuarioMouseClicked
        // TODO add your handling code here:
        MenuJuegos juegos = new MenuJuegos();
        juegos.setVisible(true);
        this.setVisible(false);
        juegos.setDefaultCloseOperation(juegos.EXIT_ON_CLOSE);
    }//GEN-LAST:event_elegirUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearUsuario;
    private javax.swing.JButton elegirUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
