/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ipc1.proyecto3.graficos;

import com.ipc1.proyecto3.controladorHanoi.Barra;
import com.ipc1.proyecto3.controladorHanoi.ControladorHanoi;
import com.ipc1.proyecto3.controladorHanoi.Torre;


/**
 *
 * @author minch
 */
public class TorresdeHanoi extends javax.swing.JFrame{

    Barra[] barras = new Barra[8];
    Torre[] torres = new Torre[3];
    private int idClico = -1;
    int cantidaBarras = 3;
    boolean terminar = false;
    
    /**
     * Creates new form TorresdeHanoi
     */
    public TorresdeHanoi() {
        
         
        //this.add(cronometro);
        
        //cronometro.setVisible(true);
        //cronometro.setBounds(300, 3, 300, 60);
        Cronometro crnmt = new Cronometro(this);
        Thread t = new Thread(crnmt);
        
        
        ControladorHanoi.instanciarBarras(barras, cantidaBarras);

        ControladorHanoi.instanciarTorres(torres);
        ControladorHanoi.iniciador(barras, torres, cantidaBarras);
        this.setLocationRelativeTo(null);
        //botones();
        
        initComponents();
        deshabilitarBarras();
        //datos();

        t.start();
       
    }

    public boolean isTerminar() {
        return terminar;
    }
    

    public void botones() {
        for (int i = 7; i > 7 - cantidaBarras; i--) {
            this.add(barras[i].getBoton());
            barras[i].getBoton().setLocation(330, (i * 40) + 145);
        }
        for (int i = 0; i < 3; i++) {
            this.add(torres[i].getTorreG());
            torres[i].getTorreG().setLocation(150 + (300 * i), 110);
        }

    }

    public void datos() {
        for (int i = 0; i < 3; i++) {
            System.out.println("peso tor " + i + ":" + torres[i].getPeso());
            System.out.println("ocupado tor " + i + ":" + torres[i].getPosOcupadas());
        }

        //Runnable cronometro = new Cronometro();
        //Thread  ter = new Thread(cronometro);
        //ter.start(); 
    }

    public void deshabilitarBarras() {
        for (int i = 0; i < 3; i++) {
            //imagen[i] = new ImageIcon("C:\\Users\\minch\\Documents\\NetBeansProjects\\Proyecto3\\src\\main\\java\\com\\ipc1\\proyecto3\\imagenes\\rectangle" + i + ".png");
        }
        //barra8.setIcon(new ImageIcon(imagen[2].getImage().getScaledInstance(290, 40, Image.SCALE_REPLICATE)));
        //barra7.setIcon(new ImageIcon(imagen[1].getImage().getScaledInstance(290, 40, Image.SCALE_REPLICATE)));
        //barra6.setIcon(new ImageIcon(imagen[0].getImage().getScaledInstance(290, 40, Image.SCALE_REPLICATE)));
        if (cantidaBarras < 8) {
            barra1.setVisible(false);
        }
        if (cantidaBarras < 7) {
            barra2.setVisible(false);
        }
        if (cantidaBarras < 6) {
            barra3.setVisible(false);
        }
        if (cantidaBarras < 5) {
            barra4.setVisible(false);
        }
        if (cantidaBarras < 4) {
            barra5.setVisible(false);
        }
    }

    public void deshabilitarTodaslasBarras() {
        barra1.setEnabled(false);
        barra2.setEnabled(false);
        barra3.setEnabled(false);
        barra4.setEnabled(false);
        barra5.setEnabled(false);
        barra6.setEnabled(false);
        barra7.setEnabled(false);
        barra8.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        barra1 = new javax.swing.JButton();
        barra2 = new javax.swing.JButton();
        barra3 = new javax.swing.JButton();
        barra4 = new javax.swing.JButton();
        barra5 = new javax.swing.JButton();
        barra6 = new javax.swing.JButton();
        barra7 = new javax.swing.JButton();
        barra8 = new javax.swing.JButton();
        torre1 = new javax.swing.JLabel();
        torre2 = new javax.swing.JLabel();
        torre3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra1.setText("1");
        barra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barra1MouseClicked(evt);
            }
        });
        jPanel2.add(barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 280, 40));

        barra2.setText("2");
        barra2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barra2MouseClicked(evt);
            }
        });
        jPanel2.add(barra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 280, 40));

        barra3.setText("3");
        barra3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barra3MouseClicked(evt);
            }
        });
        jPanel2.add(barra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 280, 40));

        barra4.setText("4");
        barra4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barra4MouseClicked(evt);
            }
        });
        jPanel2.add(barra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 280, 40));

        barra5.setText("5");
        barra5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barra5MouseClicked(evt);
            }
        });
        jPanel2.add(barra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 280, 40));

        barra6.setText("6");
        barra6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barra6MouseClicked(evt);
            }
        });
        barra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra6ActionPerformed(evt);
            }
        });
        jPanel2.add(barra6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 40));

        barra7.setText("7");
        barra7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barra7MouseClicked(evt);
            }
        });
        jPanel2.add(barra7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 280, 40));

        barra8.setText("8");
        barra8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barra8MouseClicked(evt);
            }
        });
        barra8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra8ActionPerformed(evt);
            }
        });
        jPanel2.add(barra8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 280, 40));

        torre1.setBackground(new java.awt.Color(153, 51, 0));
        torre1.setText("1");
        torre1.setOpaque(true);
        torre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                torre1MouseClicked(evt);
            }
        });
        jPanel2.add(torre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 30, 350));
        torre1.getAccessibleContext().setAccessibleName("torre1");

        torre2.setBackground(new java.awt.Color(153, 51, 0));
        torre2.setText("2");
        torre2.setOpaque(true);
        torre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                torre2MouseClicked(evt);
            }
        });
        jPanel2.add(torre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 30, 350));

        torre3.setBackground(new java.awt.Color(153, 51, 0));
        torre3.setText("3");
        torre3.setOpaque(true);
        torre3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                torre3MouseClicked(evt);
            }
        });
        jPanel2.add(torre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 30, 350));

        jButton1.setText("termiar partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void torre3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_torre3MouseClicked
        // TODO add your handling code here:
        int idTorre = 2;
        System.out.println("clictorre 3 pesotorre:" + torres[idTorre].getPeso());
        if (idClico != -1) {
            if (barras[idClico].getIdTorreActual() != idTorre) {
                if (torres[idTorre].getPeso() >= barras[idClico].getPeso()) {
                    moverBoton(idClico, 630, ControladorHanoi.posY(idTorre, torres));
                    ControladorHanoi.mover(idTorre, idClico, torres, barras);
                    idClico = -1;
                }
            }
        }

        if (cantidaBarras == torres[2].getPosOcupadas()) {
            deshabilitarTodaslasBarras();
            System.out.println("GANASTE");
        }
    }//GEN-LAST:event_torre3MouseClicked

    private void torre2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_torre2MouseClicked
        // TODO add your handling code here:
        int idTorre = 1;
        System.out.println("clictorre 2 pesotorre:" + torres[idTorre].getPeso());
        if (idClico != -1) {
            if (barras[idClico].getIdTorreActual() != idTorre) {
                if (torres[idTorre].getPeso() >= barras[idClico].getPeso()) {
                    moverBoton(idClico, 330, ControladorHanoi.posY(idTorre, torres));
                    ControladorHanoi.mover(idTorre, idClico, torres, barras);
                    idClico = -1;
                }
            }
        }
    }//GEN-LAST:event_torre2MouseClicked

    private void torre1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_torre1MouseClicked
        // TODO add your handling code here:
        int idTorre = 0;
        System.out.println("clictorre 1 pesotorre:" + torres[idTorre].getPeso());
        if (idClico != -1) {
            if (barras[idClico].getIdTorreActual() != idTorre) {
                if (torres[idTorre].getPeso() >= barras[idClico].getPeso()) {
                    moverBoton(idClico, 30, ControladorHanoi.posY(idTorre, torres));
                    ControladorHanoi.mover(idTorre, idClico, torres, barras);
                    idClico = -1;
                }
            }
        }
    }//GEN-LAST:event_torre1MouseClicked

    private void barra8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra8ActionPerformed

    private void barra8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra8MouseClicked
        // TODO add your handling code here:
        int id = 7;
        if (barras[id].getPeso() <= torres[barras[id].getIdTorreActual()].getPeso()) {
            idClico = id;
            System.out.println("clic barra " + (id + 1) + " barrapeso:" + barras[id].getPeso() + " pesotorre:" + torres[barras[id].getIdTorreActual()].getPeso());
        }
        System.out.println("clic barra " + (id + 1));
    }//GEN-LAST:event_barra8MouseClicked

    private void barra7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra7MouseClicked
        // TODO add your handling code here:
        int id = 6;
        if (barras[id].getPeso() <= torres[barras[id].getIdTorreActual()].getPeso()) {
            idClico = id;
            System.out.println("clic barra " + (id + 1) + " barrapeso:" + barras[id].getPeso() + " pesotorre:" + torres[barras[id].getIdTorreActual()].getPeso());
        }
        System.out.println("clic barra " + (id + 1));
    }//GEN-LAST:event_barra7MouseClicked

    private void barra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra6ActionPerformed

    private void barra6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra6MouseClicked
        // TODO add your handling code here:
        int id = 5;
        if (barras[id].getPeso() <= torres[barras[id].getIdTorreActual()].getPeso()) {
            idClico = id;
            System.out.println("clic barra " + (id + 1) + " barrapeso:" + barras[id].getPeso() + " pesotorre:" + torres[barras[id].getIdTorreActual()].getPeso());
        }
        System.out.println("clic barra " + (id + 1));
    }//GEN-LAST:event_barra6MouseClicked

    private void barra5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra5MouseClicked
        // TODO add your handling code here:
        int id = 4;
        if (barras[id].getPeso() <= torres[barras[id].getIdTorreActual()].getPeso()) {
            idClico = id;
            System.out.println("clic barra " + (id + 1) + " barrapeso:" + barras[id].getPeso() + " pesotorre:" + torres[barras[id].getIdTorreActual()].getPeso());
        }
        System.out.println("clic barra " + (id + 1));
    }//GEN-LAST:event_barra5MouseClicked

    private void barra4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra4MouseClicked
        // TODO add your handling code here:
        int id = 3;
        if (barras[id].getPeso() <= torres[barras[id].getIdTorreActual()].getPeso()) {
            idClico = id;
            System.out.println("clic barra " + (id + 1) + " barrapeso:" + barras[id].getPeso() + " pesotorre:" + torres[barras[id].getIdTorreActual()].getPeso());
        }
        System.out.println("clic barra " + (id + 1));
    }//GEN-LAST:event_barra4MouseClicked

    private void barra3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra3MouseClicked
        // TODO add your handling code here:
        int id = 2;
        if (barras[id].getPeso() <= torres[barras[id].getIdTorreActual()].getPeso()) {
            idClico = id;
            System.out.println("clic barra " + (id + 1) + " barrapeso:" + barras[id].getPeso() + " pesotorre:" + torres[barras[id].getIdTorreActual()].getPeso());
        }
        System.out.println("clic barra " + (id + 1));
    }//GEN-LAST:event_barra3MouseClicked

    private void barra2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra2MouseClicked
        // TODO add your handling code here:
        int id = 1;
        if (barras[id].getPeso() <= torres[barras[id].getIdTorreActual()].getPeso()) {
            idClico = id;
            System.out.println("clic barra " + (id + 1) + " barrapeso:" + barras[id].getPeso() + " pesotorre:" + torres[barras[id].getIdTorreActual()].getPeso());
        }
        System.out.println("clic barra " + (id + 1));
    }//GEN-LAST:event_barra2MouseClicked

    private void barra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra1MouseClicked
        // TODO add your handling code here:
        int id = 0;
        if (barras[id].getPeso() <= torres[barras[id].getIdTorreActual()].getPeso()) {
            idClico = id;
            System.out.println("clic barra " + (id + 1) + " barrapeso:" + barras[id].getPeso() + " pesotorre:" + torres[barras[id].getIdTorreActual()].getPeso());
        }
        System.out.println("clic barra " + (id + 1));
    }//GEN-LAST:event_barra1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        terminar = true;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void moverBoton(int queBoton, int posX, int posY) {

        switch (queBoton) {
            case 0:
                barra1.setLocation(posX, posY);
                break;
            case 1:
                barra2.setLocation(posX, posY);
                break;
            case 2:
                barra3.setLocation(posX, posY);
                break;
            case 3:
                barra4.setLocation(posX, posY);
                break;
            case 4:
                barra5.setLocation(posX, posY);
                break;
            case 5:
                barra6.setLocation(posX, posY);
                break;
            case 6:
                barra7.setLocation(posX, posY);
                break;
            case 7:
                barra8.setLocation(posX, posY);
                break;

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barra1;
    private javax.swing.JButton barra2;
    private javax.swing.JButton barra3;
    private javax.swing.JButton barra4;
    private javax.swing.JButton barra5;
    private javax.swing.JButton barra6;
    private javax.swing.JButton barra7;
    private javax.swing.JButton barra8;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel torre1;
    private javax.swing.JLabel torre2;
    private javax.swing.JLabel torre3;
    // End of variables declaration//GEN-END:variables


}
